### ISSUE TITLE
"SyntaxError: Missing parentheses in call to 'print'"

### ISSUE THREAD

**Issue by twistedpixel** [aschaeffer/sony-av-indicator#2]
Hey, I have a STR-DN1060 and I'm really keen to get this working. Tried installing on Mac and then on my Raspberry Pi (Raspbian) and both times I get the error: SyntaxError: Missing parentheses in call to 'print'

I'm not familiar with Python but I understand this is some sort of issue between Python 2 and 3 which apparently are hugely different. I imagine this particular issue is easily fixed by adding the "required parenthesis" but I didn't want to go down the road of hacking away at your code until I got your opinion!

Do you know if this is something that wouldn't be too hard to make work? I'm more than happy to thoroughly test everything with my 1060 and help with compatibility.

Thanks!

edit: full debug

```python
Traceback (most recent call last):
  File "/usr/local/bin/sonyavindicator", line 9, in <module>
    load_entry_point('sonyavindicator==0.9.0', 'console_scripts', 'sonyavindicator')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/sonyavindicator/__main__.py", line 10, in <module>
    from sonyavindicator.indicator import SonyAvIndicator
  File "/usr/local/lib/python3.4/dist-packages/sonyavindicator/indicator.py", line 12, in <module>
    import gi
  File "/usr/local/lib/python3.4/dist-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

edit: format fix :-)

**Comment by aschaeffer** [comment]
> Do you know if this is something that wouldn't be too hard to make work? I'm more than happy to thoroughly test everything with my 1060 and help with compatibility.

No, I don't think so.

It seems the error is located in the python package `gi`. Can you check this? Maybe you can fix it by installing the python 3 version of `gi`:

```
pip3 install gi
```

**Comment by twistedpixel** [comment]
You're absolutely right, it was an issue with gi. Apparently on some systems the Py3 version of gi is broken because it uses Py2 code. I fixed that and then installed all the rest of the dependencies (many of them were not on any of my systems by default).

Does this run in a GUI or is it completely CLI? I was getting another error after all that and it seemed to be to do with an "x window" or something which I assumed was because I was running the Pi headless but not sure. I'll need to look at it again.

**Comment by aschaeffer** [comment]
The UI is an [application indicator](https://askubuntu.com/questions/30334/what-application-indicators-are-available).

If you want to remove the UI part you should look into the `CommandService` if you want to send commands to the AVR and the `FeedbackWatcher` if you want to receive state updates (for example the volume has changed).

**Comment by twistedpixel** [comment]
Ah, I think I've misunderstood exactly how your software works. I am unfamiliar with application indicators (and also have almost zero experience with Python!) so I think I'll need to do a little more learning before I can get this working for my needs.

I really just needed a simple way to interact with the AVR via the command line so maybe what I should do for now is try to understand your code and port the relevant communication parts to Node or something I'm familiar with (with credit to you, of course, if I add it to GitHub!)

I appreciate your advice :)
